export const NEET_SYLLABUS: Record<string, string[]> = {
  Physics: [
    "Basic Maths & Calculus (Mathematical Tools)",
    "Vectors",
    "Units and Measurements",
    "Motion in a straight line",
    "Motion in a plane",
    "Laws of motion",
    "Work, Energy & Power",
    "Centre of mass and System of Particles",
    "Rotational Motion",
    "Gravitation",
    "Mechanical Properties of Solids",
    "Mechanical Properties of Fluids",
    "Thermal Properties of matter",
    "Kinetic Theory",
    "Thermodynamics",
    "Oscillations",
    "Waves",
    "Electric Charges and Fields",
    "Electrostatic Potential and Capacitance",
    "Current Electricity",
    "Moving Charges and Magnetism",
    "Magnetism and Matter",
    "Electromagnetic Induction",
    "Alternating Current",
    "Electromagnetic Waves",
    "Ray Optics and Optical Instruments",
    "Wave Optics",
    "Dual Nature of Radiation and Matter",
    "Atoms",
    "Nuclei",
  ],
  Chemistry: [
    "Some Basic Concept of Chemistry",
    "Redox Reaction",
    "Solutions",
    "Thermodynamics & Thermochemistry",
    "Chemical Equilibrium",
    "Ionic Equilibrium",
    "Atomic Structure",
    "Classification of Elements and Periodicity in Properties",
    "Chemical Bonding and Molecular Structure",
    "Organic Chemistry: IUPAC Nomenclature",
    "Organic Chemistry: Isomerism",
    "Organic Chemistry: GOC",
    "Hydrocarbon",
    "Electrochemistry",
    "Chemical Kinetics",
    "Haloalkanes and Haloarenes",
    "Alcohols, Ethers and Phenols",
    "Aldehydes, Ketones and Carboxylic Acids",
    "Amines",
    "Biomolecules",
    "Purification and Qualitative and quantitative analysis",
    "Coordination Compound",
    "The p-Block Elements",
    "The d- and f- block Elements",
  ],
  Biology: [
    // Botany
    "Cell - The Unit of Life",
    "Cell Cycle and Cell Division",
    "The Living World",
    "Biological Classification",
    "Plant Kingdom",
    "Morphology of Flowering Plants",
    "Anatomy of Flowering Plants",
    "Respiration in Plants",
    "Photosynthesis in Higher Plants",
    "Plant Growth and Development",
    "Sexual Reproduction in Flowering Plant",
    "Molecular Basis of Inheritance",
    "Principle of Inheritance and Variation",
    "Organisms and Population",
    "Ecosystem",
    // Zoology
    "Structural Organization in Animals",
    "Breathing and Exchange of Gases",
    "Body Fluids and Circulation",
    "Excretory Products & their Elimination",
    "Locomotion & Movement",
    "Neural Control & Coordination",
    "Chemical Coordination & Integration",
    "Animal Kingdom",
    "Biomolecules", // Note: Biomolecules is also in Chemistry, but keeping it per syllabus
    "Human Reproduction",
    "Reproductive Health",
    "Human Health and Diseases",
    "Biotechnology: Principles & Processes",
    "Biotechnology and its Applications",
    "Evolution",
    "Microbes In Human Welfare",
  ],
};

export const getAllChapters = () => {
  const chapters: { name: string; subject: string }[] = [];
  Object.entries(NEET_SYLLABUS).forEach(([subject, topics]) => {
    topics.forEach((topic) => {
      // Avoid duplicate 'Biomolecules' if we want unique chapters, but it's fine since it's per subject
      chapters.push({ name: topic, subject });
    });
  });
  return chapters;
};
